# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3bd2807aead352d7b14e05f4c30952c8cf834ce861ebc18e7dddb6fc36ce7dfd4e2d0f10ade0d16d7003b784d355fa8542f8d57bdd6fa2b56ef1e2ac4a37514

test:
  secret_key_base: ab6fb01e2c7a2b35bc55c6fd7253f505a1d6e04f6bddf556f99e5c6efdec2315a1477376155fc2c4025925a35bb4ffca335e4b218e7e77d249ed57846cd32dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
